spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  resources:
    static-locations:
      - file:///${jk.upload.base-path}

mybatis-plus:
  type-aliases-package: com.sx.jk.pojo
  configuration:
    use-generated-keys: true # 使用自动生成的主键
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除字段
      logic-delete-field: deleted
      # 代表已删除的字段值
      logic-delete-value: 1
      # 代表未删除的字段值
      logic-not-delete-value: 0